/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ltnlbelgjoqkwmvxpjwd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0bmxiZWxnam9xa3dtdnhwandkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI2NTI2NzYsImV4cCI6MjA5ODIyODY3Nn0.3ygm9h64q_3SFe2nKZUSygZvlEAWg-jBj-4KQCGeWJY"